title: "Vrajesh Rana"
author: vrajeshr
email: vrajesh.r@outlook.com
description: > 

sass:
  sass_dir: _sass

permalink: /posts/:title
texture:
  title: Vrajesh Rana
  tagline: Full-Stack Software Engineer
  date_format: "%b %-d, %Y"
  showNav: true
  style: black
  navigation:
    # - title: About Me
    #   url: "/aboutme"
    - title: Projects
      url: "/"
    # - title: Notes
    #   url: "/notes"
    - title: Resume
      url: "/resume"
  social_links:
    github: vrajeshr
    linkedIn: in/vrajeshrana

# Build settings
remote_theme: texture

plugins:
  - jekyll-seo-tag

collections:
  notes:
    output: true